### ISSUE TITLE
Default server is not started

### ISSUE THREAD

**Issue by eugene-komar-bmll** [tmux-python/libtmux#378]
Hi,

I've installed `libtmux==0.11.0` with command from example (`pip install --user libtmux`)

```
>>> import libtmux
>>> server = libtmux.Server()
>>> server.sessions[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/share/virtualenvs/JRzS0ZJ1/lib/python3.10/site-packages/libtmux/server.py", line 190, in sessions
    return self.list_sessions()
  File "/home/user/.local/share/virtualenvs/JRzS0ZJ1/lib/python3.10/site-packages/libtmux/server.py", line 185, in list_sessions
    return [Session(server=self, **s) for s in self._sessions]
  File "/home/user/.local/share/virtualenvs/JRzS0ZJ1/lib/python3.10/site-packages/libtmux/server.py", line 175, in _sessions
    return self._list_sessions()
  File "/home/user/.local/share/virtualenvs/JRzS0ZJ1/lib/python3.10/site-packages/libtmux/server.py", line 154, in _list_sessions
    raise exc.LibTmuxException(proc.stderr)
libtmux.exc.LibTmuxException: ['no server running on /tmp/tmux-1000/default']
```

but when I do `server.new_session("name")` server actually starts

**Comment by tony** [comment]
@eugene-komar-bmll Did you figure this out?

Does this run contrary to what you'd you expect?  

An unstarted server would need to have a session created if none already exists.  We can give a better error, or give an option to have `Server` automatically create a session: but that may not be desirable for everyone
