### ISSUE TITLE
libtmux 0.16.0 missing dependency on packaging module

### ISSUE THREAD

**Issue by dtrodrigues** [tmux-python/libtmux#460]
https://github.com/tmux-python/libtmux/pull/351 introduces a dependency on the `packaging` module which causes `tmuxp` to not be able to run:

```
[root@c63a3100748d /]# python3 -m pip install tmuxp==1.19.0
Collecting tmuxp==1.19.0
  Downloading tmuxp-1.19.0-py3-none-any.whl (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.4/46.4 kB 3.4 MB/s eta 0:00:00
Collecting PyYAML<7.0,>=6.0
  Downloading PyYAML-6.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (757 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 757.9/757.9 kB 26.4 MB/s eta 0:00:00
Collecting colorama>=0.3.9
  Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting libtmux<0.17.0,>=0.16.0
  Downloading libtmux-0.16.0-py3-none-any.whl (35 kB)
Installing collected packages: PyYAML, libtmux, colorama, tmuxp
Successfully installed PyYAML-6.0 colorama-0.4.6 libtmux-0.16.0 tmuxp-1.19.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[root@c63a3100748d /]# tmuxp
Traceback (most recent call last):
  File "/usr/local/bin/tmuxp", line 5, in <module>
    from tmuxp import cli
  File "/usr/local/lib/python3.11/site-packages/tmuxp/__init__.py", line 11, in <module>
    from . import cli, util
  File "/usr/local/lib/python3.11/site-packages/tmuxp/cli/__init__.py", line 14, in <module>
    from libtmux.__about__ import __version__ as libtmux_version
  File "/usr/local/lib/python3.11/site-packages/libtmux/__init__.py", line 12, in <module>
    from .pane import Pane
  File "/usr/local/lib/python3.11/site-packages/libtmux/pane.py", line 12, in <module>
    from libtmux.common import tmux_cmd
  File "/usr/local/lib/python3.11/site-packages/libtmux/common.py", line 17, in <module>
    from ._compat import LooseVersion, console_to_str, str_from_console
  File "/usr/local/lib/python3.11/site-packages/libtmux/_compat.py", line 40, in <module>
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'
```

**Comment by tony** [comment]
@dtrodrigues Thank you!

Fixed in [v0.16.1](https://pypi.org/project/libtmux/0.16.1/), tmuxp is also  [v1.19.1](https://pypi.org/project/tmuxp/1.19.1/)

If you try now, any better?

**Comment by dtrodrigues** [comment]
Looks better now. Thanks for the quick fix.

**Comment by tony** [comment]
Good to know it's resolved! Thank you for the quick check!
