### ISSUE TITLE
TmuxObjectDoesNotExist when creating libtmux.Server().new_session(attach=True)

### ISSUE THREAD

**Issue by Pipeliner** [tmux-python/libtmux#502]
```
$ python3 -c 'import libtmux ; print(libtmux.Server().new_session(attach=True))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vadim/.cache/pypoetry/virtualenvs/robots-ml-agent-PwTI9jHQ-py3.8/lib/python3.8/site-packages/libtmux/server.py", line 493, in new_session
    return Session.from_session_id(
  File "/home/vadim/.cache/pypoetry/virtualenvs/robots-ml-agent-PwTI9jHQ-py3.8/lib/python3.8/site-packages/libtmux/session.py", line 85, in from_session_id
    session = fetch_obj(
  File "/home/vadim/.cache/pypoetry/virtualenvs/robots-ml-agent-PwTI9jHQ-py3.8/lib/python3.8/site-packages/libtmux/neo.py", line 240, in fetch_obj
    raise exc.TmuxObjectDoesNotExist(
libtmux.exc.TmuxObjectDoesNotExist: Could not find object

from pyproject.toml:
[tool.poetry.dependencies]
python = "^3.8"
libtmux = {git = "https://github.com/tmux-python/libtmux/"}
tmuxp = "^1.31.0"

$ tmux -V
tmux 3.0a

$ tmuxp -V
tmuxp 1.31.0, libtmux 0.23.2

$ apt-cache policy tmux
tmux:
  Installed: 3.0a-2ubuntu0.4
  Candidate: 3.0a-2ubuntu0.4
  Version table:
 *** 3.0a-2ubuntu0.4 500
        500 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
        100 /var/lib/dpkg/status
     3.0a-2 500
        500 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages

locale
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=en_US.utf8
```

When I run this code, the session is created successfully (tmux opens up, there is a single window with text like `$2` in it, closed upon enter, and then I have a shell) but libtmux does not seem to find it.

I haven't yet tried with newer tmux since I don't have it in my repositories.

**Comment by Pipeliner** [comment]
With older version of libtmux, the error is different:
```
python3 -c 'import libtmux ; print(libtmux.Server().new_session(attach=True, session_name="r"))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/libtmux/server.py", line 567, in new_session
    session = Session(server=self, **session)
  File "/usr/lib/python3/dist-packages/libtmux/session.py", line 57, in __init__
    raise ValueError('Session requires a `session_id`')
ValueError: Session requires a `session_id`
```

**Comment by Pipeliner** [comment]
> Do you have a tmux config file? (if your environment did, it would be implicitly used)
I'll have to check, I don't remember configuring it.

> Does libtmux.Server(config_file='/dev/null)` change anything?
No, same behavior

> Does libtmux.Server().is_alive() return anything?
True

> When I run this code, the session is created successfully (tmux opens up, there is a single window with text like $2 in it, closed upon enter, and then I have a shell) but libtmux does not seem to find it.
Restated: 
1. New tmux session is created
2. It has a single window
3. The window has text like $2
4. When I press enter, it closes, the text disappears, and I have a shell inside this tmux new session window.
5. When I close the window with ^D, I get the error I mentioned: TmuxObjectDoesNotExist

**Comment by Pipeliner** [comment]
Your samples works @tony thank you! So it seems that attach=True does not work for new_session()?

I am stuck trying to make further progress though. I can't either create a window or access an existing one. 

Sometimes I get this exception though it's probably not directly related to my problems:
```
--- Logging error ---                                                                                  Traceback (most recent call last):                                                                       File "/usr/lib/python3.8/logging/__init__.py", line 1085, in emit                                    
    msg = self.format(record)                                                                          
  File "/usr/lib/python3.8/logging/__init__.py", line 929, in format                                   
    return fmt.format(record)                                                                          
  File "/usr/lib/python3.8/logging/__init__.py", line 668, in format                                   
    record.message = record.getMessage()                                                               
  File "/usr/lib/python3.8/logging/__init__.py", line 373, in getMessage                                   msg = msg % self.args                                                                              
TypeError: not all arguments converted during string formatting                                        
Call stack:                                                                                              File "main.py", line 66, in <module>                                                                 
    agent = RobotGameAgent()                                                                           
  File "main.py", line 15, in __init__                                                                     self.session = self.server.new_session(                                                            
  File "/home/vadim/.cache/pypoetry/virtualenvs/robots-ml-agent-PwTI9jHQ-py3.8/lib/python3.8/site-packa
ges/libtmux/server.py", line 481, in new_session                                                       
    logger.error("new-session", *tmux_args)                                                            
Message: 'new-session'                             
Arguments: ('-P', '-F#{session_id}', '-sRobotsGameSession', '-d', '-n', 'RobotGameWindow', '/usr/game/r
obots')
```

The script I am trying to make run (sorry for lots of commented code, I was just trying to make it work using any means possible):
```
#!/usr/bin/env python3
import os
import time
import random
import libtmux


class RobotGameAgent:
    def __init__(self):
        self.moves = ["y", "k", "u", "h", "l", "b", "j", "n", "w", "t"]
        self.server = libtmux.Server()
        # self.server.attach_session("0")
        print(self.server.sessions)
        # self.session = self.server.sessions[0]
        self.session = self.server.new_session(
            session_name="RobotsGameSession",
            # attach=True,
            kill_session=True,
            # session_id="RobotGameSession",
            window_name="RobotGameWindow",
            window_command="/usr/game/robots",
        )
        self.session.attach_session()
        # self.window = self.session.new_window(
        #     # attach=True,
        #     window_name="RobotsGameWindow",
        #     window_shell="/usr/game/robots",
        # )

        self.window = self.session.attached_window
        self.pane = self.window.attached_pane
        # self.pane.pane_start_command("/usr/game/robots")
        self.pane.send_keys("robots\n")

    def get_game_state(self):
        # Give the game some time to process
        time.sleep(5)

        # Capture the pane content
        pane_content = self.pane.capture_pane()

        # The game state is now stored in `pane_content`
        return pane_content

    def choose_move(self, game_state):
        # This is where you would add your game-playing logic
        # For now, we'll just choose a move randomly
        return random.choice(self.moves)

    def make_move(self, move):
        # Send the move to the game
        self.pane.send_keys(move)

    def play_turn(self):
        # Get the current game state
        game_state = self.get_game_state()

        # Choose a move based on the current game state
        move = self.choose_move(game_state)

        # Make the chosen move
        self.make_move(move)


# Create an instance of the agent and have it play a turn
agent = RobotGameAgent()
for _ in range(5):
    agent.play_turn()
    print("\n".join(agent.get_game_state()))
input("Press enter to exit")

```

No matter what I do, I get either `libtmux.exc.LibTmuxException: ["can't find session: $24"]` or `libtmux.exc.TmuxObjectDoesNotExist: Could not find object`

**Comment by Pipeliner** [comment]
> That means if nothing else is keeping the session alive, that error will show. Can you think of a behavior that'd be more intuitive than that?

It seems I'm generally confused by what's happening. I don't get it why the session would disappear right after creation and before new_session() has a chance to find it. Anyways, if this is an expected behavior, an exception with more specific message like "the session you created is already gone because you created it the wrong way" is more helpful than generic `libtmux.exc.LibTmuxException: ["can't find session: $24"]` or `libtmux.exc.TmuxObjectDoesNotExist: Could not find object`.

Thanks for your help so much!

**Comment by Pipeliner** [comment]
Thank you, your version works. I had to remove  `self.session.attach_session()` though because it blocks the script (this is unexpected and as far as I can see is not clearly documented). I have tried calling this from `os.fork` but it leads to some glitches with handling keyboard input. `os.spawn` may be a better fit, I might try it later. 

My confusion about `.new_session(attach=True)` is twofold:
1. Is there a situation when it works, and how is the way I was calling it "wrong" i.e. different from that scenario?
2. If I am using it the "wrong" way, how should I figure that from the error message / exception I get?
